-- Check actual table names and columns in database
USE RMMS_Production;
GO

-- List all tables
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;
GO

-- Check ByProductSales columns
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ByProductSales'
ORDER BY ORDINAL_POSITION;
GO

-- Check ExternalRiceSales columns
SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ExternalRiceSales'
ORDER BY ORDINAL_POSITION;
GO

-- Check for Loans/Advances table variants
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Loan%' OR TABLE_NAME LIKE '%Advance%'
ORDER BY TABLE_NAME;
GO

-- Check for Fixed Assets table variants
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Fixed%' OR TABLE_NAME LIKE '%Asset%'
ORDER BY TABLE_NAME;
GO

-- Check for Voucher table variants
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Voucher%'
ORDER BY TABLE_NAME;
GO

-- Check for Receivable table variants
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Receiv%'
ORDER BY TABLE_NAME;
GO

-- Check for Payable table variants
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Pay%'
ORDER BY TABLE_NAME;
GO
