-- Get exact schema for all tables to create repositories correctly
USE RMMS_Production;
GO

PRINT 'Table Schemas for Repository Creation:';
PRINT '========================================';

PRINT '';
PRINT 'ExternalRiceSales:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ExternalRiceSales' ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'RiceProcurementExternal:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RiceProcurementExternal' ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'LoansAdvances:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'LoansAdvances' ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'FixedAssets:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FixedAssets' ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'Vouchers:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Vouchers' ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'ReceivablesOverdue:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ReceivablesOverdue' ORDER BY ORDINAL_POSITION;

PRINT '';
PRINT 'PayablesOverdue:';
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'PayablesOverdue' ORDER BY ORDINAL_POSITION;

GO
