#!/usr/bin/env bash
#
# ClaudePrompt/ULTRATHINK Framework - Tailored Bashrc Configuration
# CUSTOMIZED FOR: semanticraj@Ubuntu 22.04.5 LTS (QEMU/UTM)
#
# INSTALLATION INSTRUCTIONS:
# ==========================
#
# Option 1 - Automatic Append (Recommended):
# -------------------------------------------
# bash bashrc_additions_TAILORED_semanticraj.sh
#
# Option 2 - Manual Copy-Paste:
# ------------------------------
# 1. Open ~/.bashrc in editor: nano ~/.bashrc
# 2. Scroll to bottom
# 3. Copy everything between the BASHRC_START and BASHRC_END markers below
# 4. Paste at the end of your ~/.bashrc
# 5. Save and exit
# 6. Run: source ~/.bashrc
#
# Option 3 - Direct Source:
# --------------------------
# Add this line to your ~/.bashrc:
# source /home/semanticraj/claude-test/ClaudePrompt/bashrc_additions_TAILORED_semanticraj.sh
#

# If script is sourced or executed, apply the configuration
if [ -n "$BASH_VERSION" ]; then
    # Check if already configured
    if grep -q "ULTRATHINK CONFIGURATION FOR semanticraj" ~/.bashrc 2>/dev/null; then
        echo "✓ ULTRATHINK configuration already exists in ~/.bashrc"
        echo "  No changes made."
        exit 0
    fi

    # If executed (not sourced), append to bashrc
    if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then
        echo "Installing ULTRATHINK configuration to ~/.bashrc..."

        # Backup existing bashrc
        if [ -f ~/.bashrc ]; then
            cp ~/.bashrc ~/.bashrc.backup.$(date +%Y%m%d_%H%M%S)
            echo "✓ Backed up existing .bashrc"
        fi

        # Append configuration
        cat >> ~/.bashrc << 'BASHRC_START'

# ============================================================================
# CLAUDE CODE & ULTRATHINK CONFIGURATION FOR semanticraj
# Auto-generated by bashrc_additions_TAILORED_semanticraj.sh
# Date: Generated for deployment to Ubuntu 22.04.5 LTS (QEMU/UTM)
# ============================================================================

# Claude Code Aliases
alias cc="claude --dangerously-skip-permissions"
export CLAUDE_CODE_MAX_OUTPUT_TOKENS=200000

# CRITICAL: NEVER USE API - NO CHARGES ALLOWED
# export ANTHROPIC_API_KEY=""  # NEVER UNCOMMENT - We use Claude Code only

# ============================================================================
# ULTRATHINKC - TestPrompt System
# ============================================================================
alias ultrathinkc="python3 /home/semanticraj/claude-test/TestPrompt/ultrathink.py"
alias uc="python3 /home/semanticraj/claude-test/TestPrompt/ultrathink.py"

# ============================================================================
# ClaudePrompt - Primary ULTRATHINK Instance
# IMPORTANT: Using 'ccode' instead of 'cpp' to avoid conflict with C preprocessor
# ============================================================================
alias ccode="/home/semanticraj/claude-test/ClaudePrompt/cpp"
alias cpps="/home/semanticraj/claude-test/ClaudePrompt/cpps"

# Legacy cpp alias (commented out - use ccode instead)
# alias cpp="/home/semanticraj/claude-test/ClaudePrompt/cpp"  # CONFLICT with /usr/bin/cpp

# ============================================================================
# Quick Navigation Aliases
# ============================================================================
alias cdtp='cd /home/semanticraj/claude-test/TestPrompt'
alias cdcp='cd /home/semanticraj/claude-test/ClaudePrompt'
alias cdct='cd /home/semanticraj/claude-test'

# ============================================================================
# PATH Configuration
# ============================================================================
export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

# ============================================================================
# Python Environment (for --user installations)
# ============================================================================
export PYTHONUSERBASE="$HOME/.local"

# ============================================================================
# Claude Code Environment
# ============================================================================
# These are automatically set by Claude Code, included here for documentation
# export CLAUDECODE=1
# export CLAUDE_CODE_ENTRYPOINT=cli

# ============================================================================
# ULTRATHINK Helper Functions
# ============================================================================

# Function: Quick test of ClaudePrompt
ccode_test() {
    ccode "System test: $(date)" --verbose
}

# Function: Quick test of TestPrompt
uc_test() {
    uc "System test: $(date)" --verbose
}

# Function: View latest ClaudePrompt output
ccode_latest() {
    local LATEST=$(ls -t /home/semanticraj/claude-test/ClaudePrompt/tmp/cppultrathink_output_*.txt 2>/dev/null | head -1)
    if [ -n "$LATEST" ]; then
        echo "Latest output: $LATEST"
        cat "$LATEST"
    else
        echo "No output files found"
    fi
}

# Function: View latest TestPrompt output
uc_latest() {
    if [ -f /tmp/ultrathink_output.txt ]; then
        cat /tmp/ultrathink_output.txt
    else
        echo "No output file found at /tmp/ultrathink_output.txt"
    fi
}

# Function: List all ClaudePrompt output files
ccode_list() {
    ls -lht /home/semanticraj/claude-test/ClaudePrompt/tmp/cppultrathink_output_*.txt 2>/dev/null | head -20
}

# Function: Clean old output files (keeps last 50)
ccode_clean() {
    local COUNT=$(ls /home/semanticraj/claude-test/ClaudePrompt/tmp/cppultrathink_output_*.txt 2>/dev/null | wc -l)
    if [ "$COUNT" -gt 50 ]; then
        echo "Found $COUNT output files. Keeping latest 50, removing older files..."
        ls -t /home/semanticraj/claude-test/ClaudePrompt/tmp/cppultrathink_output_*.txt | tail -n +51 | xargs rm -f
        echo "✓ Cleanup complete"
    else
        echo "Only $COUNT output files found. No cleanup needed (threshold: 50)"
    fi
}

# Function: Show ULTRATHINK system status
ultrathink_status() {
    echo "================================================================================"
    echo "ULTRATHINK System Status"
    echo "================================================================================"
    echo ""
    echo "User: $(whoami)"
    echo "Home: $HOME"
    echo "Working Directory: $(pwd)"
    echo ""
    echo "Python: $(python3 --version 2>&1)"
    echo "Claude Code: $(claude --version 2>&1 | head -1)"
    echo ""
    echo "Aliases:"
    alias | grep -E "ccode|ultrathinkc|uc|cdcp|cdtp" || echo "  No ULTRATHINK aliases found"
    echo ""
    echo "ClaudePrompt Directory:"
    if [ -d /home/semanticraj/claude-test/ClaudePrompt ]; then
        echo "  ✓ Exists: /home/semanticraj/claude-test/ClaudePrompt"
        ls /home/semanticraj/claude-test/ClaudePrompt/cpp &>/dev/null && echo "  ✓ cpp wrapper found"
        ls /home/semanticraj/claude-test/ClaudePrompt/cpps &>/dev/null && echo "  ✓ cpps wrapper found"
    else
        echo "  ✗ Not found: /home/semanticraj/claude-test/ClaudePrompt"
    fi
    echo ""
    echo "TestPrompt Directory:"
    if [ -d /home/semanticraj/claude-test/TestPrompt ]; then
        echo "  ✓ Exists: /home/semanticraj/claude-test/TestPrompt"
    else
        echo "  ✗ Not found: /home/semanticraj/claude-test/TestPrompt"
    fi
    echo ""
    echo "Python Packages:"
    pip3 list 2>/dev/null | grep -E "anthropic|requests|pyyaml|pytest|dotenv" || echo "  Critical packages not found"
    echo ""
    echo "Output Files:"
    local OUTPUT_COUNT=$(ls /home/semanticraj/claude-test/ClaudePrompt/tmp/cppultrathink_output_*.txt 2>/dev/null | wc -l)
    echo "  ClaudePrompt outputs: $OUTPUT_COUNT"
    if [ -f /tmp/ultrathink_output.txt ]; then
        echo "  TestPrompt output: ✓ exists"
    else
        echo "  TestPrompt output: ✗ not found"
    fi
    echo ""
    echo "================================================================================"
}

# ============================================================================
# Quick Help
# ============================================================================

# Function: Show ULTRATHINK quick help
ultrathink_help() {
    cat << 'HELP_EOF'
===============================================================================
ULTRATHINK Quick Reference - semanticraj@Ubuntu 22.04.5 LTS
===============================================================================

CORE COMMANDS:
--------------
  ccode "prompt" -v         Run ClaudePrompt with verbose output
  cpps "prompt" -v          Run ClaudePrompt (Para Group wrapper)
  ultrathinkc "prompt" -v   Run TestPrompt with verbose output
  uc "prompt" -v            Run TestPrompt (shorthand)

NAVIGATION:
-----------
  cdcp                      Go to ClaudePrompt directory
  cdtp                      Go to TestPrompt directory
  cdct                      Go to claude-test directory

HELPER FUNCTIONS:
-----------------
  ccode_test                Test ClaudePrompt system
  uc_test                   Test TestPrompt system
  ccode_latest              View latest ClaudePrompt output
  uc_latest                 View latest TestPrompt output
  ccode_list                List all ClaudePrompt output files
  ccode_clean               Clean old output files (keeps 50)
  ultrathink_status         Show system status
  ultrathink_help           Show this help

OUTPUT LOCATIONS:
-----------------
  ClaudePrompt: /home/semanticraj/claude-test/ClaudePrompt/tmp/cppultrathink_output_*.txt
  TestPrompt:   /tmp/ultrathink_output.txt

IMPORTANT NOTES:
----------------
  • Use 'ccode' NOT 'cpp' (cpp conflicts with C preprocessor at /usr/bin/cpp)
  • All commands work from any directory (absolute paths)
  • Verbose mode shows all [VERBOSE] stages and guardrail layers
  • Output files are timestamped and preserved

EXAMPLES:
---------
  ccode "What is 2+2?" -v
  uc "Analyze this code" --verbose
  cdcp && ls -la
  ccode_latest | less
  ultrathink_status

For full documentation, see:
  /home/semanticraj/claude-test/CLAUDE.md
  /home/semanticraj/claude-test/ClaudePrompt/CLAUDE.md

===============================================================================
HELP_EOF
}

# ============================================================================
# Auto-display help on first login
# ============================================================================

# Check if this is the first time ULTRATHINK is loaded
if [ ! -f ~/.ultrathink_welcome_shown ]; then
    echo ""
    echo "================================================================================"
    echo "🔥 ULTRATHINK Framework Loaded Successfully 🔥"
    echo "================================================================================"
    echo ""
    echo "Welcome to the ULTRATHINK orchestration system!"
    echo ""
    echo "Quick Start:"
    echo "  • Run: ultrathink_help      (show all commands)"
    echo "  • Run: ultrathink_status    (check system status)"
    echo "  • Run: ccode \"test\" -v      (test ClaudePrompt)"
    echo ""
    echo "Type 'ultrathink_help' anytime to see the quick reference."
    echo ""
    echo "================================================================================"
    touch ~/.ultrathink_welcome_shown
fi

# ============================================================================
# End of ULTRATHINK Configuration
# ============================================================================

BASHRC_START

        echo ""
        echo "================================================================================"
        echo "✅ ULTRATHINK Configuration Installed Successfully"
        echo "================================================================================"
        echo ""
        echo "NEXT STEPS:"
        echo "  1. Reload bashrc: source ~/.bashrc"
        echo "  2. Check status:  ultrathink_status"
        echo "  3. View help:     ultrathink_help"
        echo "  4. Test system:   ccode_test"
        echo ""
        echo "Configuration added to: ~/.bashrc"
        echo "Backup saved to: ~/.bashrc.backup.<timestamp>"
        echo ""
        echo "================================================================================"

        exit 0
    fi
fi

# If sourced, the configuration above will be loaded automatically
# No output when sourced to avoid cluttering terminal

BASHRC_END
